//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BotControlPanel.ControlReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ControlReference.IContolService")]
    public interface IContolService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IContolService/Query", ReplyAction="http://tempuri.org/IContolService/QueryResponse")]
        string Query();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IContolServiceChannel : BotControlPanel.ControlReference.IContolService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContolServiceClient : System.ServiceModel.ClientBase<BotControlPanel.ControlReference.IContolService>, BotControlPanel.ControlReference.IContolService {
        
        public ContolServiceClient() {
        }
        
        public ContolServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContolServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContolServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContolServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Query() {
            return base.Channel.Query();
        }
    }
}
