//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebControlPanel.Storage
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Users
    {
        public System.Guid ID { get; set; }

        [Display(Name = "Идентификатор Telegram")]
        public long TelegramID { get; set; }
        
        [Display(Name = "Имя")]
        public string FirstName { get; set; }
        
        [Display(Name = "Фамилия")]
        [MaxLength(255)]
        [Required()]
        public string LastName { get; set; }
        public string UserName { get; set; }
        public string PhoneNumber { get; set; }
        public string Description { get; set; }
        public System.DateTime TimeStamp { get; set; }

        [Display(Name = "Состояние")]
        [Range(0, 1)]
        public int State { get; set; }
        
        [EmailAddress()]
        public string EMail { get; set; }
    }
}
